#ifndef PASSENGERFLOWUI_GLOBAL_H
#define PASSENGERFLOWUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PASSENGERFLOWUI_LIBRARY)
#  define PASSENGERFLOWUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define PASSENGERFLOWUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PASSENGERFLOWUI_GLOBAL_H
