#ifndef DATABASEMODULE_GLOBAL_H
#define DATABASEMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASEMODULE_LIBRARY)
#  define DATABASEMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATABASEMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASEMODULE_GLOBAL_H
