#############################################################################
# Makefile for building: ParkSolution
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  ParkSolution.pro
# Template: subdirs
# Command: F:\Qt\Qt5.3.0\5.3\mingw482_32\bin\qmake.exe -spec win32-g++ CONFIG+=debug -o Makefile ParkSolution.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = F:\Qt\Qt5.3.0\5.3\mingw482_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-CommonModule \
		sub-ConfigModule \
		sub-AssessibilityModule \
		sub-DatabaseModule \
		sub-DataParse \
		sub-LPRModule \
		sub-NetworkModule \
		sub-VideoModule \
		sub-SerialPortModule \
		sub-ParkCustomerCenter \
		sub-ParkServer


sub-CommonModule-qmake_all:  FORCE
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd CommonModule\ && $(MAKE) -f Makefile qmake_all
sub-CommonModule: FORCE
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-CommonModule-make_first: FORCE
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-CommonModule-all: FORCE
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-CommonModule-clean: FORCE
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-CommonModule-distclean: FORCE
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-CommonModule-install_subtargets: FORCE
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-CommonModule-uninstall_subtargets: FORCE
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ConfigModule-qmake_all:  FORCE
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd ConfigModule\ && $(MAKE) -f Makefile qmake_all
sub-ConfigModule: FORCE
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-ConfigModule-make_first: FORCE
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-ConfigModule-all: FORCE
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-ConfigModule-clean: FORCE
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-ConfigModule-distclean: FORCE
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ConfigModule-install_subtargets: FORCE
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-ConfigModule-uninstall_subtargets: FORCE
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-AssessibilityModule-qmake_all:  FORCE
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd AssessibilityModule\ && $(MAKE) -f Makefile qmake_all
sub-AssessibilityModule: FORCE
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-AssessibilityModule-make_first: FORCE
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-AssessibilityModule-all: FORCE
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-AssessibilityModule-clean: FORCE
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-AssessibilityModule-distclean: FORCE
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-AssessibilityModule-install_subtargets: FORCE
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-AssessibilityModule-uninstall_subtargets: FORCE
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-DatabaseModule-qmake_all:  FORCE
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd DatabaseModule\ && $(MAKE) -f Makefile qmake_all
sub-DatabaseModule: FORCE
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-DatabaseModule-make_first: FORCE
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-DatabaseModule-all: FORCE
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-DatabaseModule-clean: FORCE
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-DatabaseModule-distclean: FORCE
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-DatabaseModule-install_subtargets: FORCE
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-DatabaseModule-uninstall_subtargets: FORCE
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-DataParse-qmake_all:  FORCE
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd DataParse\ && $(MAKE) -f Makefile qmake_all
sub-DataParse: FORCE
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-DataParse-make_first: FORCE
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-DataParse-all: FORCE
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-DataParse-clean: FORCE
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-DataParse-distclean: FORCE
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-DataParse-install_subtargets: FORCE
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-DataParse-uninstall_subtargets: FORCE
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-LPRModule-qmake_all:  FORCE
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd LPRModule\ && $(MAKE) -f Makefile qmake_all
sub-LPRModule: FORCE
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-LPRModule-make_first: FORCE
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-LPRModule-all: FORCE
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-LPRModule-clean: FORCE
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-LPRModule-distclean: FORCE
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-LPRModule-install_subtargets: FORCE
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-LPRModule-uninstall_subtargets: FORCE
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-NetworkModule-qmake_all:  FORCE
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd NetworkModule\ && $(MAKE) -f Makefile qmake_all
sub-NetworkModule: FORCE
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-NetworkModule-make_first: FORCE
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-NetworkModule-all: FORCE
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-NetworkModule-clean: FORCE
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-NetworkModule-distclean: FORCE
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-NetworkModule-install_subtargets: FORCE
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-NetworkModule-uninstall_subtargets: FORCE
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-VideoModule-qmake_all:  FORCE
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd VideoModule\ && $(MAKE) -f Makefile qmake_all
sub-VideoModule: FORCE
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-VideoModule-make_first: FORCE
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-VideoModule-all: FORCE
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-VideoModule-clean: FORCE
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-VideoModule-distclean: FORCE
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-VideoModule-install_subtargets: FORCE
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-VideoModule-uninstall_subtargets: FORCE
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-SerialPortModule-qmake_all:  FORCE
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd SerialPortModule\ && $(MAKE) -f Makefile qmake_all
sub-SerialPortModule: FORCE
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-SerialPortModule-make_first: FORCE
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-SerialPortModule-all: FORCE
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-SerialPortModule-clean: FORCE
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-SerialPortModule-distclean: FORCE
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-SerialPortModule-install_subtargets: FORCE
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-SerialPortModule-uninstall_subtargets: FORCE
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ParkCustomerCenter-qmake_all:  FORCE
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd ParkCustomerCenter\ && $(MAKE) -f Makefile qmake_all
sub-ParkCustomerCenter: FORCE
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-ParkCustomerCenter-make_first: FORCE
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-ParkCustomerCenter-all: FORCE
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-ParkCustomerCenter-clean: FORCE
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-ParkCustomerCenter-distclean: FORCE
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ParkCustomerCenter-install_subtargets: FORCE
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-ParkCustomerCenter-uninstall_subtargets: FORCE
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ParkServer-qmake_all:  FORCE
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd ParkServer\ && $(MAKE) -f Makefile qmake_all
sub-ParkServer: FORCE
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-ParkServer-make_first: FORCE
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-ParkServer-all: FORCE
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-ParkServer-clean: FORCE
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-ParkServer-distclean: FORCE
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ParkServer-install_subtargets: FORCE
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-ParkServer-uninstall_subtargets: FORCE
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: ParkSolution.pro F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/spec_pre.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/qdevice.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/device_config.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/common/shell-win32.conf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/qconfig.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/qt_functions.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/qt_config.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/spec_post.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/default_pre.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/resolve_config.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/default_post.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/win32/rtti.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/precompile_header.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/warn_on.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/win32/windows.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/testcase_targets.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/exceptions.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/yacc.prf \
		F:/Qt/Qt5.3.0/5.3/mingw482_32/mkspecs/features/lex.prf \
		ParkSolution.pro
	$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile ParkSolution.pro
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\spec_pre.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\qdevice.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\device_config.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\common\shell-win32.conf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\qconfig.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_axbase.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_axbase_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_axcontainer.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_axserver.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_axserver_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_bluetooth.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_clucene_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_concurrent.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_concurrent_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_core.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_core_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_declarative.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_declarative_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_designer.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_designer_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_enginio.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_enginio_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_gui.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_gui_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_help.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_help_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_multimedia.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_multimedia_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_network.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_network_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_nfc.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_nfc_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_opengl.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_opengl_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_openglextensions.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_positioning.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_positioning_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_printsupport.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_printsupport_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_qml.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_qml_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_qmltest.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_qmltest_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_quick.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_quick_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_quickwidgets.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_script.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_script_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_scripttools.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_scripttools_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_sensors.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_sensors_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_serialport.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_serialport_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_sql.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_sql_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_svg.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_svg_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_testlib.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_testlib_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_uitools.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_uitools_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_webkit.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_webkit_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_websockets.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_websockets_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_widgets.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_widgets_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_winextras.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_winextras_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_xml.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_xml_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\qt_functions.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\qt_config.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\win32\qt_config.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\win32-g++\qmake.conf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\spec_post.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\exclusive_builds.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\default_pre.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\win32\default_pre.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\resolve_config.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\exclusive_builds_post.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\default_post.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\win32\rtti.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\precompile_header.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\warn_on.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\win32\windows.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\testcase_targets.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\exceptions.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\yacc.prf:
F:\Qt\Qt5.3.0\5.3\mingw482_32\mkspecs\features\lex.prf:
ParkSolution.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile ParkSolution.pro

qmake_all: sub-CommonModule-qmake_all sub-ConfigModule-qmake_all sub-AssessibilityModule-qmake_all sub-DatabaseModule-qmake_all sub-DataParse-qmake_all sub-LPRModule-qmake_all sub-NetworkModule-qmake_all sub-VideoModule-qmake_all sub-SerialPortModule-qmake_all sub-ParkCustomerCenter-qmake_all sub-ParkServer-qmake_all FORCE

make_first: sub-CommonModule-make_first sub-ConfigModule-make_first sub-AssessibilityModule-make_first sub-DatabaseModule-make_first sub-DataParse-make_first sub-LPRModule-make_first sub-NetworkModule-make_first sub-VideoModule-make_first sub-SerialPortModule-make_first sub-ParkCustomerCenter-make_first sub-ParkServer-make_first FORCE
all: sub-CommonModule-all sub-ConfigModule-all sub-AssessibilityModule-all sub-DatabaseModule-all sub-DataParse-all sub-LPRModule-all sub-NetworkModule-all sub-VideoModule-all sub-SerialPortModule-all sub-ParkCustomerCenter-all sub-ParkServer-all FORCE
clean: sub-CommonModule-clean sub-ConfigModule-clean sub-AssessibilityModule-clean sub-DatabaseModule-clean sub-DataParse-clean sub-LPRModule-clean sub-NetworkModule-clean sub-VideoModule-clean sub-SerialPortModule-clean sub-ParkCustomerCenter-clean sub-ParkServer-clean FORCE
distclean: sub-CommonModule-distclean sub-ConfigModule-distclean sub-AssessibilityModule-distclean sub-DatabaseModule-distclean sub-DataParse-distclean sub-LPRModule-distclean sub-NetworkModule-distclean sub-VideoModule-distclean sub-SerialPortModule-distclean sub-ParkCustomerCenter-distclean sub-ParkServer-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-CommonModule-install_subtargets sub-ConfigModule-install_subtargets sub-AssessibilityModule-install_subtargets sub-DatabaseModule-install_subtargets sub-DataParse-install_subtargets sub-LPRModule-install_subtargets sub-NetworkModule-install_subtargets sub-VideoModule-install_subtargets sub-SerialPortModule-install_subtargets sub-ParkCustomerCenter-install_subtargets sub-ParkServer-install_subtargets FORCE
uninstall_subtargets: sub-CommonModule-uninstall_subtargets sub-ConfigModule-uninstall_subtargets sub-AssessibilityModule-uninstall_subtargets sub-DatabaseModule-uninstall_subtargets sub-DataParse-uninstall_subtargets sub-LPRModule-uninstall_subtargets sub-NetworkModule-uninstall_subtargets sub-VideoModule-uninstall_subtargets sub-SerialPortModule-uninstall_subtargets sub-ParkCustomerCenter-uninstall_subtargets sub-ParkServer-uninstall_subtargets FORCE

sub-CommonModule-debug:
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-ConfigModule-debug:
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-AssessibilityModule-debug:
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-DatabaseModule-debug:
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-DataParse-debug:
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-LPRModule-debug:
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-NetworkModule-debug:
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-VideoModule-debug:
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-SerialPortModule-debug:
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-ParkCustomerCenter-debug:
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-ParkServer-debug:
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-CommonModule-debug sub-ConfigModule-debug sub-AssessibilityModule-debug sub-DatabaseModule-debug sub-DataParse-debug sub-LPRModule-debug sub-NetworkModule-debug sub-VideoModule-debug sub-SerialPortModule-debug sub-ParkCustomerCenter-debug sub-ParkServer-debug

sub-CommonModule-release:
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-ConfigModule-release:
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-AssessibilityModule-release:
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-DatabaseModule-release:
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-DataParse-release:
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-LPRModule-release:
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-NetworkModule-release:
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-VideoModule-release:
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-SerialPortModule-release:
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-ParkCustomerCenter-release:
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-ParkServer-release:
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-CommonModule-release sub-ConfigModule-release sub-AssessibilityModule-release sub-DatabaseModule-release sub-DataParse-release sub-LPRModule-release sub-NetworkModule-release sub-VideoModule-release sub-SerialPortModule-release sub-ParkCustomerCenter-release sub-ParkServer-release

sub-CommonModule-check:
	@if not exist CommonModule\ mkdir CommonModule\ & if not exist CommonModule\ exit 1
	cd CommonModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\CommonModule\CommonModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-ConfigModule-check:
	@if not exist ConfigModule\ mkdir ConfigModule\ & if not exist ConfigModule\ exit 1
	cd ConfigModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ConfigModule\ConfigModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-AssessibilityModule-check:
	@if not exist AssessibilityModule\ mkdir AssessibilityModule\ & if not exist AssessibilityModule\ exit 1
	cd AssessibilityModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\AssessibilityModule\AssessibilityModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-DatabaseModule-check:
	@if not exist DatabaseModule\ mkdir DatabaseModule\ & if not exist DatabaseModule\ exit 1
	cd DatabaseModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DatabaseModule\DatabaseModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-DataParse-check:
	@if not exist DataParse\ mkdir DataParse\ & if not exist DataParse\ exit 1
	cd DataParse\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\DataParse\DataParse.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-LPRModule-check:
	@if not exist LPRModule\ mkdir LPRModule\ & if not exist LPRModule\ exit 1
	cd LPRModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\LPRModule\LPRModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-NetworkModule-check:
	@if not exist NetworkModule\ mkdir NetworkModule\ & if not exist NetworkModule\ exit 1
	cd NetworkModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\NetworkModule\NetworkModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-VideoModule-check:
	@if not exist VideoModule\ mkdir VideoModule\ & if not exist VideoModule\ exit 1
	cd VideoModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\VideoModule\VideoModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-SerialPortModule-check:
	@if not exist SerialPortModule\ mkdir SerialPortModule\ & if not exist SerialPortModule\ exit 1
	cd SerialPortModule\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\SerialPortModule\SerialPortModule.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-ParkCustomerCenter-check:
	@if not exist ParkCustomerCenter\ mkdir ParkCustomerCenter\ & if not exist ParkCustomerCenter\ exit 1
	cd ParkCustomerCenter\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkCustomerCenter\ParkCustomerCenter.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-ParkServer-check:
	@if not exist ParkServer\ mkdir ParkServer\ & if not exist ParkServer\ exit 1
	cd ParkServer\ && ( if not exist Makefile $(QMAKE) D:\ParkSolution\ParkServer\ParkServer.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-CommonModule-check sub-ConfigModule-check sub-AssessibilityModule-check sub-DatabaseModule-check sub-DataParse-check sub-LPRModule-check sub-NetworkModule-check sub-VideoModule-check sub-SerialPortModule-check sub-ParkCustomerCenter-check sub-ParkServer-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

