#ifndef SERIALPORTMODULE_GLOBAL_H
#define SERIALPORTMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALPORTMODULE_LIBRARY)
#  define SERIALPORTMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERIALPORTMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALPORTMODULE_GLOBAL_H
