#ifndef ASSESSIBLILITYMODULE_GLOBAL_H
#define ASSESSIBLILITYMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASSESSIBLILITYMODULE_LIBRARY)
#  define ASSESSIBLILITYMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ASSESSIBLILITYMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ASSESSIBLILITYMODULE_GLOBAL_H
