#ifndef CONFIGMODULE_GLOBAL_H
#define CONFIGMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONFIGMODULE_LIBRARY)
#  define CONFIGMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONFIGMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONFIGMODULE_GLOBAL_H
